/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
	const Code: (typeof import('$components/options/OptionsCode.astro'))['default'];
	const Example: (typeof import('$components/options/OptionsExample.astro'))['default'];
	const Examples: (typeof import('$components/options/OptionsExamples.svelte'))['default'];
}
