#!/usr/bin/env node
"use strict";

var _chunkUCZTHOL6js = require('./chunk-UCZTHOL6.js');
require('./chunk-UWWD4V4J.js');


var _chunkOUMKCN57js = require('./chunk-OUMKCN57.js');
require('./chunk-EBJAWNYG.js');

// src/cli-default.ts
_chunkUCZTHOL6js.main.call(void 0, ).catch(_chunkOUMKCN57js.handleError);
