#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../prebuild-install@7.1.1/node_modules/prebuild-install/bin.js" "$@"
else
  exec node  "$basedir/../../../../../prebuild-install@7.1.1/node_modules/prebuild-install/bin.js" "$@"
fi
