#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../strong-log-transformer@2.1.0/node_modules/strong-log-transformer/bin/sl-log-transformer.js" "$@"
else
  exec node  "$basedir/../../../../../strong-log-transformer@2.1.0/node_modules/strong-log-transformer/bin/sl-log-transformer.js" "$@"
fi
