export {
	clickElement,
	dragAndDrop,
	dragUsingKeyboard,
	getCursorPosition,
	getCursorPositionRelativeToElement,
	getElementCoords,
	isCursorOverElement,
	mouseClick,
	mouseDoubleClick,
	mouseDown,
	mouseMove,
	mouseUp,
	mouseWheel,
	startCursorTracking,
	stopCursorTracking,
	type MouseButton,
	type MouseMoveOptions,
	type MouseOptions,
} from '../../tests/mouse.ts';
